### ISSUE TITLE
There is no linked app associated with this client ID even though app was set up and working long ago

### ISSUE THREAD

**Issue by Krauxe** [playgameservices/management-tools#14]
Hi!

I have replaced the app ID (9xxxxxxxxxxx) and client ID (9xxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com) properly but I'm still getting an error. I can log in but I'm greeted with the error "There is no linked app associated with this client ID" even though Game Services have been integrated and working long ago. I can see some requests failing with 401. See screenshot below:
![play games management console error](https://cloud.githubusercontent.com/assets/10218615/5468640/c053c9c2-860c-11e4-93cc-820a8ed4c21c.PNG)

Response body:
```
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "UnregisteredClientId",
    "message": "There is no linked app associated with this client ID."
   }
  ],
  "code": 401,
  "message": "There is no linked app associated with this client ID."
 }
}
```

Any ideas?

**Comment by jimmithy** [comment]
Hey, ran into this problem today and figured out how to fix it.

Go to the Google Play Console, and then Game Services. Under your application, select Linked Apps, and then Link New App.

Select Web, and if you created a new client Id in the API console, it will alert you to link a pre-existing app. Fill out all the info and you should be good to go!

**Comment by 4k-developer** [comment]
Ok thx

**Comment by Krauxe** [comment]
@jimmithy Late reply but thanks! Turns out the app was not linked properly and the client ID was defined in the Google API Console instead of through the Google Play Console ~.~
