### ISSUE TITLE
Linked Web Application Required?

### ISSUE THREAD

**Issue by NaxIonz** [playgameservices/management-tools#16]
We are developing our game for Android, and trying to use these tools just so we can reset achievements on test devices.

However, I can't seem to connect to the game when clicking "Sign In"

![screenshot 2015-01-05 19 04 52](https://cloud.githubusercontent.com/assets/1693810/5622780/88b94544-950e-11e4-935c-77f93022bb77.png)

Am I required to have a linked Web application even for a mobile game?

**Comment by ToddKerpelman** [comment]
Yes, you need to have a linked Web application if you're intending to use the management tools. That's what allows the tool to sign-in to the same set of services that your Android game is using.

**Comment by NaxIonz** [comment]
Does it matter what URL I use for that linked Web application?

Can we just use the landing page of our company? Or does it actually need to link to a "game?"

Is there any other way to reset the achievements without doing all this? (That's all we are trying to accomplish with these tools)

**Comment by samtstern** [comment]
@NaxIonz this is the easiest way to reset.  Once you link a web application and run this tool it will be one click.

**Comment by NaxIonz** [comment]
@samtstern 
Can you clarify what I actually need to link to for a mobile game? We don't actually have any "Web Game/Application" so I am not quite sure what we are supposed to be filling out there just to get this tool working.

**Comment by samtstern** [comment]
You just need to get a client ID for web.  For the URL of the application
put localhost:8000 (or whatever port you will use with python
SimpleHTTPServer -m).  There does not need to be a web 'game'.

**Comment by NaxIonz** [comment]
Many thanks - 
I will relay that to our producer so he can set it up tomorrow, and I will attempt again :-)
