### ISSUE TITLE
Hiding/Unhiding Player Error

### ISSUE THREAD

**Issue by sozeray** [playgameservices/management-tools#19]
Hello,

I can successfully play around with achievements and list the current high scores, but when I try to hide a specific player, I pick the ID out and push the "Hide" button, and nothing happens. No feedback or anything. And when I refresh the leaderboard, the player is still there. More interestingly, when I test the "Unhide" button on any player, I get the message below:

![screen shot 2015-04-30 at 22 43 27](https://cloud.githubusercontent.com/assets/6353299/7421219/94909372-ef8b-11e4-8683-b083f9767b5f.png)

I believe I set the client ID and everything correct but, here they are:

![screen shot 2015-04-30 at 22 48 06](https://cloud.githubusercontent.com/assets/6353299/7421220/967c91f4-ef8b-11e4-9611-5946f9f5c8d0.png)

I'm using simple python localhost HTTPServer with default port (8000). Also, I'm logged in with the publisher account, which is also listed among testers. I don't know if this is an actual issue, so I'm sorry if I messed up.

Thank you.

**Comment by gguuss** [comment]
Make sure that you have the numeric-only app ID set in js/constants.js and your full client ID is specified in demo.html - for example, if your client ID is
925626146219-0h1t8td0salbp6i10hlmqsqrajfgzij.apps.googleusercontent.com...

925626146219-0h1t8td0salbp6i10hlmqsqrajfgzij.apps.googleusercontent.com - goes into demo.html as your CLIENT ID
925626146219 - goes into js/constants.js as your APP ID, this is also available from the play apps console.

**Comment by StephaneDupont** [comment]
I've got the exact same problem (and yes, my client ID and APP ID are correct).

Did you manage to resolve it @sozeray ?

**Comment by gguuss** [comment]
A few ideas:
* The Client ID was not created using the [Play Games Console](https://play.google.com/apps/publish/)
* The host name you're using hasn't been added to the authorized origins

**Comment by StephaneDupont** [comment]
Thank you @gguuss 

Do you mean you have to use the Play Games Console, and not use https://console.developers.google.com to create credentials? If yes, what's the proper way to do it, adding a "web" linked app in the "Linked apps" section?

**Comment by StephaneDupont** [comment]
That was it. Thank for pointing me in the right direction.

**Comment by gguuss** [comment]
Closing, happy the fix worked for you @StephaneDupont! @sozeray please reopen if you're continuing to experience the issue.
