### ISSUE TITLE
It has been a whole day and I haven't reset my testers' achievements yet

### ISSUE THREAD

**Issue by ChrisWhatever1980** [playgameservices/management-tools#22]
Look, I landed here because I want to reset the achievements for my testers.
Why do I have to use node.js, npm, bower, polymer, a github repository, python and a web server to do one simple task???
Why can't I just reset the achievements? What is the point in jumping through all these hoops?
So my issue is this: 
Resetting your testers' achievements is too complicated. Make it easier.

**Comment by samtstern** [comment]
@ChrisWhatever1980 this is just a wrapper around the [Management API](https://developers.google.com/games/services/management/api/).  It's meant to be a demonstration and not the main way to use the API.

Visit that link and you can make some simple REST requests to reset achievements.
